# The name as it appears through out the site
name: "A Survey Name"

# The default copyright if used
copyright: "Your Name"

#####################################################
# Questions
#####################################################

# The default is the button, where the user selects only one
button: "button"

# Checboxes will appear based on the values of answer, 
# a value of other will be replaced by the function replaceother
checkbox: "checkbox"
replaceother: "replaceOther"

# Text boxes will appear based on the number of answers
# Blank answers will yield larger text boxes, while non-blank
# answers will be used as labels
textbox: "textbox"

# In the event that a reaction is necessary based on a result
# set the skip conditional to the element (this), condition,
# number to skip if true, number to skip if false
skipconditional: "setSkipConditional"

# The value of a field that is known as other
other: "Other"